Import Required Libraries

In [18]:
import numpy as np 
import pandas as pd 
import mysql.connector
from sqlalchemy import create_engine

importing file

In [19]:
df=pd.read_csv(r"D:/DATA_ANALYST/projects/e-commerce/raw data/olist_order_payments.csv")

DATASET SHAPE

In [3]:
# Objective:
# Determine the number of rows and columns in the dataset to understand its overall size and structure.

df.shape

# Observation:
# The dataset contains 103886 rows and 5 columns.

# Insight:
# The dataset is sufficiently large for order item-level analysis and provides detailed information about purchased products.

(103886, 5)

DATASET INFO

In [4]:
# Objective:
# Examine the dataset structure, data types, non-null values, and memory usage.

df.info()

# Observation:
# • Total Records : 103,886
# • Total Columns : 5
# • Data Types    : 2 Object, 2 Integer, 1 Float
# • Missing Values: None
# • Memory Usage  : Approximately 4.0 MB

# Insight:
# The dataset is structurally complete with appropriate data types and does not require datatype or missing value corrections at this stage.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

FIRST FIVE RECORDS (HEAD)

In [5]:
# Objective:
# Display the first five records to understand the dataset structure and verify successful loading.

df.head(5)

# Observation:
# The first five records display order_id,payment_sequential,payment_type,payment_installments,payment_value

# Insight:
# The dataset appears to be loaded correctly and provides transaction-level
# information for each purchased item.

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

DESCRIPTIVE STATISTICS

In [6]:
# Objective:
# Summarize the numerical and categorical columns to understand the dataset.

df.describe(include='all')

# Observation:
# The dataset contains 103,886 payment records with 99,440 unique orders.
# Credit card is the most commonly used payment method.

# Insight:
# The dataset provides useful information on payment methods, installments,
# and payment values for further analysis.

,order_id,payment_sequential,payment_type,payment_installments,payment_value
count,103886,103886.000000,103886,103886.000000,103886.000000
unique,99440,NaN,5,NaN,NaN
top,fa65dad1b0e818e3ccc5cb0e39231352,NaN,credit_card,NaN,NaN
freq,29,NaN,76795,NaN,NaN
mean,NaN,1.092679,NaN,2.853349,154.100380
std,NaN,0.706584,NaN,2.687051,217.494064
min,NaN,1.000000,NaN,0.000000,0.000000
25%,NaN,1.000000,NaN,1.000000,56.790000
50%,NaN,1.000000,NaN,1.000000,100.000000
75%,NaN,1.000000,NaN,4.000000,171.837500
max,NaN,29.000000,NaN,24.000000,13664.080000

DATASET COLUMNS

In [7]:
# Objective:
# Review the available columns and verify that the naming convention is clear and consistent.

df.columns

# Observation:
# The dataset contains five well-defined columns.

# Insight:
# The column names are meaningful and will simplify analysis, SQL table
# creation, and relationships with other datasets.

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='object')

CHECKING MISSING VALUES

In [8]:
# Objective:
# Identify missing values in each column to determine whether data cleaning is required.

df.isnull().sum()

# Observation:
# No missing values were found in any column.

# Insight:
# The dataset is complete and does not require missing value treatment.

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

CHECKING DUPLICATES VALUES

In [9]:
# Objective:
# Identify duplicate records that may affect data quality.

df.duplicated().sum()

# Observation:
# No duplicate records were found in the dataset.

# Insight:
# Every record is unique, indicating good data quality and no need for duplicate removal.

np.int64(0)

CHECKING UNIQUE VALUES

In [10]:
# Objective:
# Determine the number of unique values in each column to understand
# data uniqueness and identify key attributes.

df.nunique()

# Observation:
# order_id has 98,666 unique values, product_id has 32,951 unique values,
# seller_id has 3,095 unique values, while order_item_id ranges from 1 to 21.

# Insight:
# The uniqueness analysis confirms that multiple products can belong to
# the same order, which is expected in an order items dataset.

order_id                99440
payment_sequential         29
payment_type                5
payment_installments       24
payment_value           29077
dtype: int64

CHECKING DATATYPES

In [11]:
# Objective:
# Verify that each column has the appropriate data type for analysis.

df.dtypes

# Observation:
# The dataset contains four object columns, one integer column,
# and two floating-point columns.

# Insight:
# The current data types are appropriate for analysis and require no conversion.

order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

VALIDATING   UNIQUENESS

In [17]:
# Objective:
# Verify that the combination of order_id and payment_sequential
# uniquely identifies each payment record.

df[["order_id", "payment_sequential"]].duplicated().sum()

# Observation:
# No duplicate combinations of order_id and payment_sequential
# were found.

# Insight:
# Insight:
# The combination of order_id and payment_sequential uniquely
# identifies each payment transaction and confirms the integrity
# of the payment dataset.

np.int64(0)

IMPORTING FILE TO MYSQL

In [21]:
engine = create_engine(
    "mysql+mysqlconnector://root:H%40rshita2@localhost/ecommerce_db"
)

with engine.connect() as conn:
    print("Connected successfully!")

df.to_sql(
    "order_payments_clean",
    con=engine,
    if_exists="replace",
    index=False
)

Connected successfully!

103886