Import Required Libraries

In [3]:
import numpy as np 
import pandas as pd 
import mysql.connector
from sqlalchemy import create_engine

importing file

In [4]:
df=pd.read_csv(r"D:/DATA_ANALYST/projects/e-commerce/raw data/olist_order_reviews.csv")

DATASET SHAPE

In [4]:
# Objective:
# Determine the number of rows and columns in the dataset to understand its overall size and structure.

df.shape

# Observation:
# The dataset contains 99,224 rows and 7 columns.

# Insight:
# The dataset is sufficiently large for order item-level analysis and provides detailed information about purchased products.

(99224, 7)

DATASET INFO

In [6]:
# Objective:
# Examine the dataset structure, data types, non-null values, and memory usage.

df.info()

# Observation:
# • Total Records : 99,224
# • Total Columns : 7
# • Data Types    : 6 Object, 1 Integer

# • Missing Values: None
# • Memory Usage  : Approximately 5.3 MB

# Insight:
# The dataset is structurally complete with appropriate data types and does not require datatype or missing value corrections at this stage.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

FIRST FIVE RECORDS (HEAD)

In [8]:
# Objective:
# Display the first five records to understand the dataset structure and verify successful loading.

df.head()

# Observation:
# The first five records display review_id,order_id	,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp

# Insight:
# The dataset appears to be loaded correctly and provides transaction-level
# information for each purchased item.

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

DESCRIPTIVE STATISTICS

In [9]:
# Objective:
# Summarize the numerical and categorical columns to understand the dataset.

df.describe(include='all')

# Observation:
# The dataset contains 103,886 payment records with 99,440 unique orders.
# Credit card is the most commonly used payment method.

# Insight:
# The dataset provides useful information on payment methods, installments,
# and payment values for further analysis.

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
count,99224,99224,99224.000000,11568,40977,99224,99224
unique,98410,98673,NaN,4527,36159,636,98248
top,7b606b0d57b078384f0b58eac1d41d78,c88b1d1b157a9999ce368f218a407141,NaN,Recomendo,Muito bom,2017-12-19 00:00:00,2017-06-15 23:21:05
freq,3,3,NaN,423,230,463,4
mean,NaN,NaN,4.086421,NaN,NaN,NaN,NaN
std,NaN,NaN,1.347579,NaN,NaN,NaN,NaN
min,NaN,NaN,1.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,4.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,5.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,5.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,5.000000,NaN,NaN,NaN,NaN

DATASET COLUMNS

In [11]:
# Objective:
# Review the available columns and verify that the naming convention is clear and consistent.

df.columns

# Observation:
# The dataset contains seven well-defined columns.

# Insight:
# The column names are meaningful and will simplify analysis, SQL table
# creation, and relationships with other datasets.

Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='object')

CHECKING MISSING VALUES

In [13]:
# Objective:
# Identify missing values in each column to determine whether data cleaning is required.

df.isnull().sum()

# Observation:
# Missing values were found in review_comment_title and
# review_comment_message.

# Insight:
# These columns are optional. The missing values indicate that
# some customers provided only a rating without a written review.
# Therefore, no rows were removed.

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

CHECKING DUPLICATES VALUES

In [14]:
# Objective:
# Identify duplicate records that may affect data quality.

df.duplicated().sum()

# Observation:
# No duplicate records were found in the dataset.

# Insight:
# Every record is unique, indicating good data quality and no need for duplicate removal.

np.int64(0)

CHECKING UNIQUE VALUES

In [15]:
# Objective:
# Determine the number of unique values in each column to understand
# data uniqueness and identify key attributes.

df.nunique()

# Observation:
# order_id has 98,666 unique values, product_id has 32,951 unique values,
# seller_id has 3,095 unique values, while order_item_id ranges from 1 to 21.

# Insight:
# The uniqueness analysis confirms that multiple products can belong to
# the same order, which is expected in an order items dataset.

review_id                  98410
order_id                   98673
review_score                   5
review_comment_title        4527
review_comment_message     36159
review_creation_date         636
review_answer_timestamp    98248
dtype: int64

CHECKING DATATYPES

In [16]:
# Objective:
# Verify that each column has the appropriate data type for analysis.

df.dtypes

# Observation:
# The dataset contains six object columns, one integer column,
# and two floating-point columns.

# Insight:
# The current data types are appropriate for analysis and require no conversion.

review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

VALIDATING ORDER ID UNIQUENESS

In [20]:
# Objective:
# Verify whether each order is associated with only one review record.

df["order_id"].nunique() == len(df)

# Observation:
# The validation returned False, indicating that some orders have
# multiple review records.

# Insight:
# This suggests that a small number of orders are associated with more
# than one review entry. These records should be investigated further
# before deciding whether any cleaning is required.

False

IMPORTING TO MYSQL

In [5]:
engine = create_engine(
    "mysql+mysqlconnector://root:H%40rshita2@localhost/ecommerce_db"
)

with engine.connect() as conn:
    print("Connected successfully!")

df.to_sql(
    "order_reviews_clean",
    con=engine,
    if_exists="replace",
    index=False
)

Connected successfully!

99224