Import Required Libraries

In [3]:
import numpy as np 
import pandas as pd 
import mysql.connector
from sqlalchemy import create_engine

importing file

In [4]:
df=pd.read_csv(r"D:/DATA_ANALYST/projects/e-commerce/raw data/olist_orders.csv")

DATASET SHAPE

In [4]:
# Objective:
# Determine the number of rows and columns in the dataset to understand its overall size and structure.

df.shape

# Observation:
# The dataset contains 99,441 rows and 8 columns.

# Insight:
# The dataset is sufficiently large for order item-level analysis and provides detailed information about purchased products.

(99441, 8)

DATASET INFO

In [6]:
# Objective:
# Examine the dataset structure, data types, non-null values, and memory usage.

df.info()

# Observation:
# • Total Records : 99,441
# • Total Columns : 8
# • Data Types    : 8 Object

# • Missing Values: None
# • Memory Usage  : Approximately 6.1 MB

# Insight:
# The dataset is structurally complete with appropriate data types and does not require datatype or missing value corrections at this stage.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

FIRST FIVE RECORDS (HEAD)

In [8]:
# Objective:
# Display the first five records to understand the dataset structure and verify successful loading.

df.head()

# Observation:
# The first five records display order_id,customer_id	,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date

# Insight:
# The dataset appears to be loaded correctly and provides transaction-level
# information for each purchased item.

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

DESCRIPTIVE STATISTICS

In [10]:
# Objective:
# Summarize the numerical and categorical columns to understand the dataset.

df.describe(include='all')

# Observation:
# The dataset contains 103,886 payment records with 99,441 unique orders.
# Credit card is the most commonly used payment method.

# Insight:
# The dataset provides useful information on payment methods, installments,
# and payment values for further analysis.

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2018-04-11 10:48:14,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-08 23:38:46,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

DATASET COLUMNS

In [11]:
# Objective:
# Review the available columns and verify that the naming convention is clear and consistent.

df.columns

# Observation:
# The dataset contains seven well-defined columns.

# Insight:
# The column names are meaningful and will simplify analysis, SQL table
# creation, and relationships with other datasets.

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

CHECKING MISSING VALUES

In [13]:
# Objective:
# Identify missing values in each column to determine whether
# data cleaning is required.

df.isnull().sum()

# Observation:
# Missing values were found in order_approved_at,
# order_delivered_carrier_date, and order_delivered_customer_date.
# All other columns are complete.

# Insight:
# These missing values are expected because some orders may have been
# cancelled, unavailable, or not yet delivered. Therefore, these records
# should be retained for further analysis.

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

CHECKING DUPLICATES VALUES

In [14]:
# Objective:
# Identify duplicate records that may affect data quality.

df.duplicated().sum()

# Observation:
# No duplicate records were found in the dataset.

# Insight:
# Every record is unique, indicating good data quality and no need for duplicate removal.

np.int64(0)

CHECKING UNIQUE VALUES

In [16]:
# Objective:
# Determine the number of unique values in each column to understand
# data uniqueness and identify key attributes.

df.nunique()

# Observation:
# all columns have following unique vales

# Insight:
# The uniqueness analysis confirms that multiple products can belong to
# the same order, which is expected in an order items dataset.

order_id                         99441
customer_id                      99441
order_status                         8
order_purchase_timestamp         98875
order_approved_at                90733
order_delivered_carrier_date     81018
order_delivered_customer_date    95664
order_estimated_delivery_date      459
dtype: int64

CHECKING DATATYPES

In [ ]:
# Objective:
# Verify that each column has the appropriate data type for analysis.

df.dtypes

# Observation:
# The dataset contains six object columns.

# Insight:
# The current data types are appropriate for analysis and require no conversion.

VALIDATING ORDER ID UNIQUENESS

In [23]:
# Objective:
# Verify that each order_id uniquely identifies a single order record.

df["order_id"].nunique() == len(df)

# Observation:
# The validation returned True, confirming that every order_id is unique.

# Insight:
# order_id serves as a unique identifier for each order and can be
# reliably used to establish relationships with other tables.

True

IMPORTING TO MYSQL

In [5]:
engine = create_engine(
    "mysql+mysqlconnector://root:H%40rshita2@localhost/ecommerce_db"
)

with engine.connect() as conn:
    print("Connected successfully!")

df.to_sql(
    "order_clean",
    con=engine,
    if_exists="replace",
    index=False
)

Connected successfully!

99441