Import Required Libraries

In [49]:
import numpy as np 
import pandas as pd 
import mysql.connector
from sqlalchemy import create_engine

importing file

In [50]:
df=pd.read_csv(r"D:/DATA_ANALYST/projects/e-commerce/raw data/olist_products.csv")

DATASET SHAPE

In [36]:
# Objective:
# Determine the number of rows and columns in the dataset to understand its overall size and structure.

df.shape

# Observation:
# The dataset contains 32,951 rows and 9 columns.

# Insight:
# The dataset is sufficiently large for order item-level analysis and provides detailed information about purchased products.

(32951, 9)

DATASET INFO

In [37]:
# Objective:
# Examine the dataset structure, data types, non-null values, and memory usage.

df.info()

# Observation:
# • Total Records : 32,951
# • Total Columns : 9
# • Data Types    : 2 Object , 7 Float

# • Missing Values: None
# • Memory Usage  : Approximately 2.3 MB

# Insight:
# The dataset is structurally complete with appropriate data types and does not require datatype or missing value corrections at this stage.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

FIRST FIVE RECORDS (HEAD)

In [38]:
# Objective:
# Display the first five records to understand the dataset structure and verify successful loading.

df.head(5)

# Observation:
# The  records display product_id	,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm	,product_height_cm,product_width_cm

# Insight:
# The dataset appears to be loaded correctly and provides transaction-level
# information for each purchased item.

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

DESCRIPTIVE STATISTICS

In [39]:
# Objective:
# Summarize the numerical and categorical columns to understand the
# structure and characteristics of the dataset.

df.describe(include='all')

# Observation:
# The dataset contains 32,951 products across 73 product categories.
# Product dimensions, weight, description length, and photo counts
# vary significantly across products.

# Insight:
# The dataset provides detailed product information that can be used
# to analyze product characteristics, categories, and physical attributes.

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32951,32341,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
unique,32951,73,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,1e9e8ef04dbcff4541ed26657ea517e5,cama_mesa_banho,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,3029,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,NaN,NaN,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,NaN,NaN,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,NaN,NaN,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,NaN,NaN,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,NaN,NaN,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,NaN,NaN,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

DATASET COLUMNS

In [40]:
# Objective:
# Review the available columns and verify that the naming convention is clear and consistent.

df.columns

# Observation:
# The dataset contains seven well-defined columns.

# Insight:
# The column names are meaningful and will simplify analysis, SQL table
# creation, and relationships with other datasets.

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

CHECKING MISSING VALUES

In [41]:
# Objective:
# Identify missing values in each column to determine whether
# data cleaning is required.

df.isnull().sum()

# Observation:
# Missing values were found in order_approved_at,
# order_delivered_carrier_date, and order_delivered_customer_date.
# All other columns are complete.

# Insight:
# These missing values are expected because some orders may have been
# cancelled, unavailable, or not yet delivered. Therefore, these records
# should be retained for further analysis.

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [42]:
df = df.dropna(how="all", subset=[
    "product_category_name",
    "product_name_lenght",
    "product_description_lenght",
    "product_photos_qty",
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
])

In [43]:
df.isnull().sum()
# Observation:
# After removing one completely incomplete record, 609 products still
# contain missing descriptive information, and one product has missing
# physical dimensions.

# Insight:
# These records were retained because they contain useful business
# information. Removing or imputing these values without sufficient
# evidence could introduce bias into the dataset.

product_id                      0
product_category_name         609
product_name_lenght           609
product_description_lenght    609
product_photos_qty            609
product_weight_g                1
product_length_cm               1
product_height_cm               1
product_width_cm                1
dtype: int64

CHECKING DUPLICATES VALUES

In [44]:
# Objective:
# Identify duplicate records that may affect data quality.

df.duplicated().sum()

# Observation:
# No duplicate records were found in the dataset.

# Insight:
# Every record is unique, indicating good data quality and no need for duplicate removal.

np.int64(0)

CHECKING UNIQUE VALUES

In [45]:
# Objective:
# Determine the number of unique values in each column to understand
# data uniqueness and identify key attributes.

df.nunique()

# Observation:
# all columns have following unique vales

# Insight:
# The uniqueness analysis confirms that multiple products can belong to
# the same order, which is expected in an order items dataset.

product_id                    32950
product_category_name            73
product_name_lenght              66
product_description_lenght     2960
product_photos_qty               19
product_weight_g               2204
product_length_cm                99
product_height_cm               102
product_width_cm                 95
dtype: int64

CHECKING DATATYPES

In [46]:
# Objective:
# Verify that each column has the appropriate data type for analysis.

df.dtypes

# Observation:
# The dataset contains two object ,7 float columns.

# Insight:
# The current data types are appropriate for analysis and require no conversion.

product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

VALIDATING ORDER ID UNIQUENESS

In [51]:
# Objective:
# Verify that each order_id uniquely identifies a single order record.

df["product_id"].nunique() == len(df)

# Observation:
# The validation returned True, confirming that every order_id is unique.

# Insight:
# order_id serves as a unique identifier for each order and can be
# reliably used to establish relationships with other tables.

True

IMPORTNG TO MYSQL

In [52]:
engine = create_engine(
    "mysql+mysqlconnector://root:H%40rshita2@localhost/ecommerce_db"
)

with engine.connect() as conn:
    print("Connected successfully!")

df.to_sql(
    "products_clean",
    con=engine,
    if_exists="replace",
    index=False
)

Connected successfully!

32951