Import Required Libraries

In [43]:
import numpy as np 
import pandas as pd 
import mysql.connector
from sqlalchemy import create_engine

importing file

In [44]:
df=pd.read_csv(r"D:/DATA_ANALYST/projects/e-commerce/raw data/olist_sellers.csv")

DATASET SHAPE

In [30]:
# Objective:
# Determine the number of rows and columns in the dataset to understand its overall size and structure.

df.shape

# Observation:
# The dataset contains 3,095 rows and 4 columns.

# Insight:
# The dataset is sufficiently large for order item-level analysis and provides detailed information about purchased products.

(3095, 4)

DATASET INFO

In [31]:
# Objective:
# Examine the dataset structure, data types, non-null values, and memory usage.

df.info()

# Observation:
# • Total Records : 3,095
# • Total Columns : 4
# • Data Types    : 3 Object , 1 integer

# • Missing Values: None
# • Memory Usage  : Approximately 96.8 kb

# Insight:
# The dataset is structurally complete with appropriate data types and does not require datatype or missing value corrections at this stage.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

FIRST FIVE RECORDS (HEAD)

In [32]:
# Objective:
# Display the first five records to understand the dataset structure and verify successful loading.

df.head(5)

# Observation:
# The  records display seller_id,seller_zip_code_prefix	,seller_city,seller_state
# Insight:
# The dataset appears to be loaded correctly and provides transaction-level
# information for each purchased item.

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

DESCRIPTIVE STATISTICS

In [33]:
# Objective:
# Summarize the numerical and categorical columns to understand the
# structure and characteristics of the dataset.

df.describe(include='all')

# Observation:
# The dataset contains 3, products across 73 product categories.
# Product dimensions, weight, description length, and photo counts
# vary significantly across products.

# Insight:
# The dataset provides detailed product information that can be used
# to analyze product characteristics, categories, and physical attributes.

,seller_id,seller_zip_code_prefix,seller_city,seller_state
count,3095,3095.000000,3095,3095
unique,3095,NaN,611,23
top,3442f8959a84dea7ee197c632cb2df15,NaN,sao paulo,SP
freq,1,NaN,694,1849
mean,NaN,32291.059451,NaN,NaN
std,NaN,32713.453830,NaN,NaN
min,NaN,1001.000000,NaN,NaN
25%,NaN,7093.500000,NaN,NaN
50%,NaN,14940.000000,NaN,NaN
75%,NaN,64552.500000,NaN,NaN
max,NaN,99730.000000,NaN,NaN

DATASET COLUMNS

In [34]:
# Objective:
# Review the available columns and verify that the naming convention is clear and consistent.

df.columns

# Observation:
# The dataset contains seven well-defined columns.

# Insight:
# The column names are meaningful and will simplify analysis, SQL table
# creation, and relationships with other datasets.

Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'], dtype='object')

CHECKING MISSING VALUES

In [35]:
# Objective:
# Identify missing values in each column to determine whether
# data cleaning is required.

df.isnull().sum()

# Observation:
# Missing values were found in order_approved_at,
# order_delivered_carrier_date, and order_delivered_customer_date.
# All other columns are complete.

# Insight:
# These missing values are expected because some orders may have been
# cancelled, unavailable, or not yet delivered. Therefore, these records
# should be retained for further analysis.

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [36]:
df = df.dropna(how="all", subset=[
    "product_category_name",
    "product_name_lenght",
    "product_description_lenght",
    "product_photos_qty",
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
])

KeyError: ['product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

In [37]:
df.isnull().sum()
# Observation:
# After removing one completely incomplete record, 609 products still
# contain missing descriptive information, and one product has missing
# physical dimensions.

# Insight:
# These records were retained because they contain useful business
# information. Removing or imputing these values without sufficient
# evidence could introduce bias into the dataset.

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

CHECKING DUPLICATES VALUES

In [38]:
# Objective:
# Identify duplicate records that may affect data quality.

df.duplicated().sum()

# Observation:
# No duplicate records were found in the dataset.

# Insight:
# Every record is unique, indicating good data quality and no need for duplicate removal.

np.int64(0)

CHECKING UNIQUE VALUES

In [39]:
# Objective:
# Determine the number of unique values in each column to understand
# data uniqueness and identify key attributes.

df.nunique()

# Observation:
# all columns have following unique vales

# Insight:
# The uniqueness analysis confirms that multiple products can belong to
# the same order, which is expected in an order items dataset.

seller_id                 3095
seller_zip_code_prefix    2246
seller_city                611
seller_state                23
dtype: int64

CHECKING DATATYPES

In [40]:
# Objective:
# Verify that each column has the appropriate data type for analysis.

df.dtypes

# Observation:
# The dataset contains two object ,7 float columns.

# Insight:
# The current data types are appropriate for analysis and require no conversion.

seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

VALIDATING ORDER ID UNIQUENESS

In [45]:
# Objective:
# Verify that each order_id uniquely identifies a single order record.

df["seller_id"].nunique() == len(df)

# Observation:
# The validation returned True, confirming that every order_id is unique.

# Insight:
# order_id serves as a unique identifier for each order and can be
# reliably used to establish relationships with other tables.

True

IMPORTING MYSQL

In [46]:
engine = create_engine(
    "mysql+mysqlconnector://root:H%40rshita2@localhost/ecommerce_db"
)

with engine.connect() as conn:
    print("Connected successfully!")

df.to_sql(
    "sellers_clean",
    con=engine,
    if_exists="replace",
    index=False
)

Connected successfully!

3095